In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

In [18]:
train_X = pd.read_csv("light_train_source_labels.csv")
train_X = train_X.drop("user_id", axis=1)
train_y = pd.read_csv("light_train_target_labels.csv")
train_y = train_y.drop("user_id", axis=1)

# Convert the data into the appropriate format for the LSTM model
train_X = np.array(train_X)
train_X = train_X.reshape(train_X.shape[0], train_X.shape[1], 1)  # Reshape to (samples, timesteps, features)

In [21]:
# Create the LSTM model
model = Sequential()
model.add(LSTM(units=64, input_shape=(train_X.shape[1], 1)))
model.add(Dense(units=28, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy')

# Fit the model on the training data
model.fit(train_X, train_y, epochs=1, batch_size=128)




238/238 [==============================] - 308s 1s/step - loss: 0.3889


In [22]:
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_5 (LSTM)               (None, 64)                16896     
                                                                 
 dense_5 (Dense)             (None, 28)                1820      
                                                                 
Total params: 18,716
Trainable params: 18,716
Non-trainable params: 0
_________________________________________________________________
None


In [49]:
# # Predict the next 28 timeslots
test_x = pd.read_csv("light_test_source_labels.csv")
test_x = preprocess_df(test_x)
test_x = test_x.reshape(test_x.shape[0], test_x.shape[1], 1)

result = model.predict(test_x)
# result = result.flatten()

# Print the predicted timeslots
print(result)

238/238 [==============================] - 22s 94ms/step
[[0.24358709 0.3461375  0.07955156 ... 0.25804263 0.05699122 0.04244659]
 [0.23139587 0.32588884 0.07736883 ... 0.24583533 0.05106803 0.03942245]
 [0.23134847 0.32582337 0.0773496  ... 0.24577993 0.05105868 0.03940961]
 ...
 [0.23385051 0.328804   0.0784635  ... 0.24858004 0.05171164 0.04026574]
 [0.23107937 0.32551518 0.07725272 ... 0.24558531 0.05100381 0.03936331]
 [0.23138878 0.32590038 0.07737023 ... 0.24586903 0.05106619 0.03943002]]


In [50]:
display(result.shape)
display(type(result))
result = result.transpose()
display(result)

(7616, 28)

numpy.ndarray

array([[0.24358709, 0.23139587, 0.23134847, ..., 0.23385051, 0.23107937,
        0.23138878],
       [0.3461375 , 0.32588884, 0.32582337, ..., 0.328804  , 0.32551518,
        0.32590038],
       [0.07955156, 0.07736883, 0.0773496 , ..., 0.0784635 , 0.07725272,
        0.07737023],
       ...,
       [0.25804263, 0.24583533, 0.24577993, ..., 0.24858004, 0.24558531,
        0.24586903],
       [0.05699122, 0.05106803, 0.05105868, ..., 0.05171164, 0.05100381,
        0.05106619],
       [0.04244659, 0.03942245, 0.03940961, ..., 0.04026574, 0.03936331,
        0.03943002]], dtype=float32)

IndexError: index 7615 is out of bounds for axis 0 with size 28

In [60]:
sample = pd.read_csv("sample.csv")
display(sample)

user_id  time_slot_0  time_slot_1  time_slot_2  time_slot_3  \
0       30460          0.0          0.0          0.0          0.0   
1       30461          0.0          0.0          0.0          0.0   
2       30462          0.0          0.0          0.0          0.0   
3       30463          0.0          0.0          0.0          0.0   
4       30464          0.0          0.0          0.0          0.0   
...       ...          ...          ...          ...          ...   
7611    38071          0.0          0.0          0.0          0.0   
7612    38072          0.0          0.0          0.0          0.0   
7613    38073          0.0          0.0          0.0          0.0   
7614    38074          0.0          0.0          0.0          0.0   
7615    38075          0.0          0.0          0.0          0.0   

      time_slot_4  time_slot_5  time_slot_6  time_slot_7  time_slot_8  ...  \
0             0.0          0.0          0.0          0.0          0.0  ...   
1             0.0          0.0          0.0          0.0          0.0  ...   
2             0.0          0.0          0.0          0.0          0.0  ...   
3             0.0          0.0          0.0          0.0          0.0  ...   
4             0.0          0.0          0.0          0.0          0.0  ...   
...           ...          ...          ...          ...          ...  ...   
7611          0.0          0.0          0.0          0.0          0.0  ...   
7612          0.0          0.0          0.0          0.0          0.0  ...   
7613          0.0          0.0          0.0          0.0          0.0  ...   
7614          0.0          0.0          0.0          0.0          0.0  ...   
7615          0.0          0.0          0.0          0.0          0.0  ...   

      time_slot_18  time_slot_19  time_slot_20  time_slot_21  time_slot_22  \
0              0.0           0.0           0.0           0.0           0.0   
1              0.0           0.0           0.0           0.0           0.0   
2              0.0           0.0           0.0           0.0           0.0   
3              0.0           0.0           0.0           0.0           0.0   
4              0.0           0.0           0.0           0.0           0.0   
...            ...           ...           ...           ...           ...   
7611           0.0           0.0           0.0           0.0           0.0   
7612           0.0           0.0           0.0           0.0           0.0   
7613           0.0           0.0           0.0           0.0           0.0   
7614           0.0           0.0           0.0           0.0           0.0   
7615           0.0           0.0           0.0           0.0           0.0   

      time_slot_23  time_slot_24  time_slot_25  time_slot_26  time_slot_27  
0              0.0           0.0           0.0           0.0           0.0  
1              0.0           0.0           0.0           0.0           0.0  
2              0.0           0.0           0.0           0.0           0.0  
3              0.0           0.0           0.0           0.0           0.0  
4              0.0           0.0           0.0           0.0           0.0  
...            ...           ...           ...           ...           ...  
7611           0.0           0.0           0.0           0.0           0.0  
7612           0.0           0.0           0.0           0.0           0.0  
7613           0.0           0.0           0.0           0.0           0.0  
7614           0.0           0.0           0.0           0.0           0.0  
7615           0.0           0.0           0.0           0.0           0.0  

[7616 rows x 29 columns]

In [61]:
print(7616*28)

213248


In [70]:
answer = sample
# answer.iloc[:,1:] = result
for i in range(1,29):
    answer.iloc[:,i] = result[i-1]
display(answer)

user_id  time_slot_0  time_slot_1  time_slot_2  time_slot_3  \
0       30460     0.243587     0.346137     0.079552     0.054315   
1       30461     0.231396     0.325889     0.077369     0.049910   
2       30462     0.231348     0.325823     0.077350     0.049895   
3       30463     0.231079     0.325515     0.077253     0.049808   
4       30464     0.231083     0.325518     0.077254     0.049809   
...       ...          ...          ...          ...          ...   
7611    38071     0.231079     0.325515     0.077253     0.049808   
7612    38072     0.233865     0.328818     0.078468     0.050781   
7613    38073     0.233851     0.328804     0.078464     0.050775   
7614    38074     0.231079     0.325515     0.077253     0.049808   
7615    38075     0.231389     0.325900     0.077370     0.049907   

      time_slot_4  time_slot_5  time_slot_6  time_slot_7  time_slot_8  ...  \
0        0.219035     0.291474     0.052241     0.043202     0.153874  ...   
1        0.199337     0.288292     0.051803     0.041325     0.146161  ...   
2        0.199311     0.288310     0.051806     0.041313     0.146178  ...   
3        0.199185     0.288385     0.051833     0.041266     0.146204  ...   
4        0.199187     0.288385     0.051832     0.041266     0.146205  ...   
...           ...          ...          ...          ...          ...  ...   
7611     0.199185     0.288385     0.051833     0.041266     0.146204  ...   
7612     0.200773     0.288270     0.052001     0.042204     0.145823  ...   
7613     0.200766     0.288272     0.052002     0.042201     0.145821  ...   
7614     0.199185     0.288385     0.051832     0.041266     0.146204  ...   
7615     0.199342     0.288287     0.051808     0.041332     0.146140  ...   

      time_slot_18  time_slot_19  time_slot_20  time_slot_21  time_slot_22  \
0         0.052386      0.038601      0.147767      0.283596      0.048677   
1         0.051196      0.035467      0.143079      0.276771      0.047487   
2         0.051184      0.035465      0.143080      0.276772      0.047481   
3         0.051138      0.035446      0.143028      0.276868      0.047468   
4         0.051138      0.035447      0.143029      0.276865      0.047468   
...            ...           ...           ...           ...           ...   
7611      0.051138      0.035446      0.143028      0.276868      0.047468   
7612      0.052090      0.035768      0.143430      0.277050      0.048052   
7613      0.052088      0.035767      0.143424      0.277058      0.048052   
7614      0.051138      0.035446      0.143028      0.276868      0.047468   
7615      0.051203      0.035465      0.143061      0.276802      0.047495   

      time_slot_23  time_slot_24  time_slot_25  time_slot_26  time_slot_27  
0         0.047021      0.173224      0.258043      0.056991      0.042447  
1         0.041633      0.162761      0.245835      0.051068      0.039422  
2         0.041613      0.162716      0.245780      0.051059      0.039410  
3         0.041515      0.162539      0.245585      0.051004      0.039363  
4         0.041516      0.162541      0.245587      0.051005      0.039364  
...            ...           ...           ...           ...           ...  
7611      0.041515      0.162539      0.245585      0.051004      0.039363  
7612      0.042673      0.164994      0.248588      0.051715      0.040268  
7613      0.042668      0.164986      0.248580      0.051712      0.040266  
7614      0.041515      0.162539      0.245585      0.051004      0.039363  
7615      0.041635      0.162781      0.245869      0.051066      0.039430  

[7616 rows x 29 columns]

In [76]:
answer.to_csv("submit.csv", index=False)